<a href="https://colab.research.google.com/github/ROrodrigp/ProgramacionCienciaDatos/blob/main/numpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy: Utilizar arreglos y matrices "a la matlab"
import numpy as np 

In [ ]:
v = np.array([1,2,3,4,5])
type(v)

numpy.ndarray

In [ ]:
v.shape

(5,)

In [ ]:
v.ndim

1

In [ ]:
v.dtype

dtype('int64')

In [ ]:
v+v

array([ 2,  4,  6,  8, 10])

In [ ]:
v*v

array([ 1,  4,  9, 16, 25])

In [ ]:
7.18*v

array([ 7.18, 14.36, 21.54, 28.72, 35.9 ])

In [ ]:
v @ v

55

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
m = np.array([[1,2,4],[4,5,6],[7,8,9]])
type(m)

numpy.ndarray

In [ ]:
m + m

array([[ 2,  4,  8],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
m *m

array([[ 1,  4, 16],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
m @m 

array([[ 37,  44,  52],
       [ 66,  81, 100],
       [102, 126, 157]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
r = np.random.random((3,5))*100
r

array([[59.09818095, 44.9970519 , 86.99635687, 72.57768929,  3.04811099],
       [18.0710468 , 98.50067366, 98.07724363, 41.29666536, 25.79840928],
       [88.53849824,  5.984973  , 40.94371355, 70.8411069 , 57.31244199]])

In [ ]:
#Transpuesta
rt = r.T
rt

array([[59.09818095, 18.0710468 , 88.53849824],
       [44.9970519 , 98.50067366,  5.984973  ],
       [86.99635687, 98.07724363, 40.94371355],
       [72.57768929, 41.29666536, 70.8411069 ],
       [ 3.04811099, 25.79840928, 57.31244199]])

In [ ]:
rt[1,2]

5.984973004840876

In [ ]:
rt[:,2]

array([88.53849824,  5.984973  , 40.94371355, 70.8411069 , 57.31244199])

In [ ]:
rt[2:5,1:3]

array([[98.07724363, 40.94371355],
       [41.29666536, 70.8411069 ],
       [25.79840928, 57.31244199]])

In [ ]:
rt > 45

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [ ]:
rt[rt>40]

array([59.09818095, 88.53849824, 44.9970519 , 98.50067366, 86.99635687,
       98.07724363, 40.94371355, 72.57768929, 41.29666536, 70.8411069 ,
       57.31244199])

In [ ]:
rt.sum()
#Suma de toda la matriz

812.082162399378

In [ ]:
#0 es para la suma de columnas, 1 para la suma de filas 
rt.sum(axis=0)

array([266.71738999, 281.74403873, 263.62073368])

In [ ]:
rt.sum(axis=1)

array([165.70772599, 149.48269856, 226.01731405, 184.71546155,
        86.15896226])

In [ ]:
rt.std()

30.844621912063584

In [ ]:
rt.std(axis=0)

array([28.75717134, 35.0517417 , 28.12569444])

In [ ]:
rt.mean()

54.1388108266252

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2 = a.reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
v = np.array([7,8,9])
m = np.array([[1,2,3],[4,5,6]])

In [ ]:
v.shape

(3,)

In [ ]:
m.shape

(2, 3)

In [ ]:
v+m

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
v = np.array([8,9])
m = np.array([[1,2,3],[4,5,6]]).T
m.shape


(3, 2)

In [ ]:
m

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
v+m

array([[ 9, 13],
       [10, 14],
       [11, 15]])

In [ ]:
v*m

array([[ 8, 36],
       [16, 45],
       [24, 54]])

In [ ]:
m@v

array([44, 61, 78])